spring:
  application:
    name: HerculaneumTranscriptor

  jpa:
    hibernate:
      ddl-auto: update # creates needed tables if they don't exist

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  # use database instance
  datasource:
    url: jdbc:postgresql://localhost:5432/scrolls
    username: sa
    password: sa

api:
  user:
    pageSize: 64
  scrolls:
    storageDirectory: ./uploads/scrolls
    useCloud: true

security:
  # jwt expiration time in milliseconds
  expiration: 3600000 # (1 hour)
  # secret base64 string for jwt key generation
  secret: 074575585bd48a11cf09a250c39c8bfc32878f11d057b3bf265cd1901563cd1a
  rootProfile:
    username: root
    password: root