openapi: 3.0.3
info:
  title: User management API
  description: |-
    This API specifies the operations that can be performed on user profiles.
  version: 1.0.11
servers:
  - url: https://localhost:8080/
tags:
  - name: user
    description: Operations on user profiles

paths:
  /user:
    post:
      tags:
        - user
      summary: Log in as a user
      description: Any client may attempt logging in as an existing user.
      operationId: loginUser
      requestBody:
        description: Information for logging in
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginInfo'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        default:
          description: Unexpected error
          $ref: '#/components/responses/Error'

  /register:
    post:
      tags:
        - user
      summary: Create user
      description: Any client may register a new user.
      operationId: createUser
      requestBody:
        description: Created user object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegisterInfo'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        default:
          description: Unexpected error
          $ref: '#/components/responses/Error'

  /permissions/{username}:

    put:
      tags:
        - user
      summary: Update user permissions
      description: This can only be done by `root` or `admin` users.
      operationId: updateUserPermissions

      security:
        - bearerAuth: []
      parameters:
        - name: username
          in: path
          description: Username to be updated
          required: true
          schema:
            type: string
      requestBody:
        description: Update an existing user's access level
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePermissions'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid username supplied
          $ref: '#/components/responses/Error'
        '404':
          description: User not found
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /user/{username}:
    get:
      tags:
        - user
      summary: Get user by user name
      description: Returns public access information for a given user.
      operationId: getUserByName

      parameters:
        - name: username
          in: path
          description: 'The name that needs to be fetched. Use user1 for testing. '
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        '400':
          description: Invalid username supplied
          $ref: '#/components/responses/Error'
        '404':
          description: User not found
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

    put:
      tags:
        - user
      summary: Update user information
      description: This can only be done by the same user, an admin or root user.
      operationId: updateUser

      security:
        - bearerAuth: []
      parameters:
        - name: username
          in: path
          description: Username to be updated
          required: true
          schema:
            type: string
      requestBody:
        description: Update an existing user's information, including password
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegisterInfo'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid username supplied
          $ref: '#/components/responses/Error'
        '404':
          description: User not found
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

    delete:
      tags:
        - user
      summary: Delete user
      description: This can only be done by the logged in user.
      operationId: deleteUser

      security:
        - bearerAuth: []
      parameters:
        - name: username
          in: path
          description: The name that needs to be deleted
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Invalid username supplied
          $ref: '#/components/responses/Error'
        '404':
          description: User not found
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

components:
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
      content:
        application/json:
          schema:
            type: string
    Error:
      description: Default error message bearer
      content:
        application/json:
          schema:
            type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    BasicUserInfo:
      type: object
      properties:
        username:
          type: string
          example: JohnDoe
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        contact:
          type: string
          example: johndoe@email.com

    UserInfo:
      type: object
      properties:
        basic_info:
          $ref: "#/components/schemas/BasicUserInfo"
        permissions:
          type: string
          description: >
            These are the possible permission access levels for a user:
              * `root` - Only one root user can exist, but they can perform any operation except changing their permission level.
              * `admin` - Except changing `root` user permissions, they can perform any operation.
              * `write` - Can read and write new annotations.
              * `read` - Can only read annotations from other users.
          enum:
            - root
            - admin
            - write
            - read
          example: read

    ChangePermissions:
      type: object
      properties:
        permissions:
          type: string
          description: Note that a user cannot be promoted to `root`.
          enum:
            - admin
            - write
            - read
          example: read

    UserLoginInfo:
      type: object
      properties:
        user_name:
          type: string
          example: 'JohnDoe'
        password:
          type: string
          example: '12345'

    UserRegisterInfo:
      type: object
      properties:
        basic_info:
          $ref: "#/components/schemas/BasicUserInfo"
        password:
          type: string
          example: '12345'