package com.mf.HerculaneumTranscriptor.domain.mapper;

import annotation.dto.BoxRegion;
import annotation.dto.NewBoxRegion;
import com.mf.HerculaneumTranscriptor.domain.Annotation;
import com.mf.HerculaneumTranscriptor.domain.Coordinates;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public interface AnnotationMapper {
  @Mapping(target = "id", ignore = true)
  @Mapping(target = "regionId", ignore = true) // Generated by the service
  @Mapping(target = "author", ignore = true)   // Set by the service
  @Mapping(target = "scroll", ignore = true)   // Set by the service
  @Mapping(target = "certaintyScore", ignore = true) // Defaults to 0
  @Mapping(target = "createdAt", ignore = true)
  @Mapping(target = "updatedAt", ignore = true)
  @Mapping(source = "coordinates", target = "coordinates") // Maps the nested coordinates DTO
  Annotation newBoxRegionDtoToAnnotationEntity(NewBoxRegion newBoxRegion);

  @Mapping(source = "author.username", target = "authorUsername")
  @Mapping(source = "transcription", target = "basicInfo.transcription")
  @Mapping(source = "coordinates", target = "basicInfo.coordinates")
  BoxRegion annotationEntityToBoxRegionDto(Annotation annotation);

  Coordinates coordinatesDtoToEntityCoordinates(annotation.dto.Coordinates coordinatesDto);
}
