package com.mf.HerculaneumTranscriptor.domain.mapper;

import com.mf.HerculaneumTranscriptor.domain.Comment;
import comment.dto.CommentContent;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public interface CommentMapper {
  @Mapping(target = "id", ignore = true)
  @Mapping(target = "commentId", ignore = true) // Generated by the service
  @Mapping(target = "author", ignore = true)   // Set by the service
  @Mapping(target = "annotation", ignore = true) // Set by the service
  @Mapping(target = "createdAt", ignore = true)
  @Mapping(target = "updatedAt", ignore = true)
  Comment commentContentDtoToCommentEntity(CommentContent commentContent);

  @Mapping(source = "author.username", target = "authorUsername")
  comment.dto.Comment commentEntityToCommentDto(Comment comment);
}
